package com.ngai.payment.model.repository;

import com.ngai.payment.model.entity.TPaymentProviders;
import java.lang.Short;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 12/07/2022
*/
@Repository
public interface TPaymentProvidersRepository extends JpaRepository<TPaymentProviders, Short>, JpaSpecificationExecutor<TPaymentProviders> {
    public List<TPaymentProviders> findByStrPaymentCode(String strPaymentCode);
    public List<TPaymentProviders> findByStrDriverClassName(String strDriverClassName);
}