package com.ngai.payment.model.repository;

import com.ngai.payment.model.entity.TReceivedCallback;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.Date;

/**
* Generated by Spring Data Generator on 17/07/2022
*/
@Repository
public interface TReceivedCallbackRepository extends JpaRepository<TReceivedCallback, String>, JpaSpecificationExecutor<TReceivedCallback> {
    @Modifying
    @Query(value = "INSERT INTO `t_received_callback`(`lg_trace_id`, `str_status`, `dt_date_created`) VALUES (?1, ?2, ?3);", nativeQuery = true)
    void insertReceivedCallback(String traceId, String status, Date date);

}
